Multi-variable orthogonal polynomials
Functions
gint mop_number_of_terms (gint dim, gint order)
mop_polynomial_t * mop_polynomial_alloc (gint np, gint dim, gint order)
gint mop_polynomial_free (mop_polynomial_t *p)
mop_polynomial_workspace_t * mop_polynomial_workspace_alloc (gint np, gint dim, gint order)
gint mop_polynomial_workspace_free (mop_polynomial_workspace_t *w)
gint mop_polynomial_set_points (mop_polynomial_t *p, gdouble *x, gdouble *w, gint n)
gint mop_polynomial_write (mop_polynomial_t *p, FILE *f)
gint mop_polynomial_basis_power (mop_polynomial_t *p, gint order, gdouble tol, mop_polynomial_workspace_t *w)
gint mop_polynomial_basis_points (mop_polynomial_t *p, gint order, gdouble tol, mop_polynomial_workspace_t *w)
gint mop_polynomial_make (mop_polynomial_t *p, mop_polynomial_workspace_t *w)
gint mop_polynomial_write_latex (mop_polynomial_t *p, FILE *f)
gint mop_polynomial_normalize (mop_polynomial_t *p, mop_polynomial_workspace_t *w)
gint mop_polynomial_eval (mop_polynomial_t *p, gdouble *x, gdouble *P)
gint mop_polynomial_eval_base (mop_polynomial_t *p, gdouble *P)
Detailed Description
Function Documentation
gint mop_number_of_terms (gint dim, gint order)
The number of monomials required for a multi-variable polynomial of a given order.
Parameters
dim dimension of system;
order order of polynomial.
Returns
number of terms in general polynomial of order order in dim dimensions.
Referenced by mop_polynomial_alloc(), and mop_polynomial_workspace_alloc().
mop_polynomial_t* mop_polynomial_alloc (gint np, gint dim, gint order)
Allocate a ::mop_polynomial.
Parameters
np (maximum) number of points in basis;
dim dimension of system;
order maximum order of polynomial to be generated.
Returns
pointer to new ::mop_polynomial.
References mop_number_of_terms().
gint mop_polynomial_basis_points (mop_polynomial_t * p, gint order, gdouble tol, mop_polynomial_workspace_t * w)
Generate the basis for a ::mop_polynomial_t by selecting sufficient points to match the number of monomial powers supplied.
Parameters
p a ::mop_polynomial, which should have been initialized by a call to mop_polynomial_set_points;
order maximum order of monomial to employed;
tol tolerance to be used in determining rank of basis matrix;
w suitably sized ::mop_polynomial_workspace.
Returns
MOP_SUCCESS on success
gint mop_polynomial_basis_power (mop_polynomial_t * p, gint order, gdouble tol, mop_polynomial_workspace_t * w)
Generate the basis for a ::mop_polynomial_t by selecting sufficient monomial powers to match the number of points in the ::mop_polynomial, using the method of Xu, Yuan, 2004, `On discrete orthogonal polynomials of several variables', Advances in Applied Mathematics, 33:615--632, doi:10.1016/j.aam.2004.03.002.
Parameters
p a ::mop_polynomial, which should have been initialized by a call to mop_polynomial_set_points;
order maximum order of monomial to be employed;
tol tolerance to be used in determining rank of basis matrix;
w suitably sized ::mop_polynomial_workspace.
Returns
MOP_SUCCESS on success or MOP_NO_BASIS if no basis can be generated on the points and weights supplied.
gint mop_polynomial_eval (mop_polynomial_t * p, gdouble * x, gdouble * P)
Evaluate a ::mop_polynomial_t at a point x.
Parameters
p ::mop_polynomial_t to evaluate;
x coordinates of evaluation point;
P array containing values of p at x.
Returns
MOP_SUCCESS on success.
Referenced by mop_interpolation_weights().
gint mop_polynomial_eval_base (mop_polynomial_t * p, gdouble * P)
Evaluate a ::mop_polynomial_t at its base points. Note that the base points used are those in the index list of p and they are used in the order in that list. To connect a given value of orthogonal polynomial to a particular base point, use ::mop_polynomial_index.
Parameters
p ::mop_polynomial_t to evaluate;
P array of p evaluated at its base points so that $P_{i}(x_{j})$ is P[j*mop_polynomial_nterms(p)+i].
Returns
MOP_SUCCESS on success.
Referenced by mop_differentiation_weights(), mop_interpolation_weights(), mop_polynomial_normalize(), and mop_polynomial_transform().
gint mop_polynomial_free (mop_polynomial_t * p)
Free a ::mop_polynomial_t and associated memory
Parameters
p ::mop_polynomial_t to free.
Returns
MOP_SUCCESS on success.
gint mop_polynomial_make (mop_polynomial_t * p, mop_polynomial_workspace_t * w)
Generate the discrete orthogonal polynomials associated with p, using the method of Xu, Yuan, 2004, `On discrete orthogonal polynomials of several variables', Advances in Applied Mathematics, 33:615--632, doi:10.1016/j.aam.2004.03.002.
Parameters
p a ::mop_polynomial, which should have been initialized by a call to mop_polynomial_basis_power or mop_polynomial_basis_points;
w a suitably sized ::mop_polynomial_workspace, generated by mop_polynomial_workspace_alloc.
Returns
MOP_SUCCESS on success.
gint mop_polynomial_normalize (mop_polynomial_t * p, mop_polynomial_workspace_t * w)
Scale the coefficients of a ::mop_polynomial_t to give unit inner product, $\sum_{i}P_{j}^{2}(x_{i})w_{i}\equiv 1$.
Parameters
p ::mop_polynomial_t to normalize;
w a ::mop_polynomial_workspace_t of appropriate size.
Returns
MOP_SUCCESS on success.
References mop_polynomial_eval_base().
gint mop_polynomial_set_points (mop_polynomial_t * p, gdouble * x, gdouble * w, gint n)
Set points and weights to be used in generating sets of orthogonal polynomials. The data are copied into p so the arrays can be reused.
Parameters
p a ::mop_polynomial_t of appropriate size;
x array of points of the same dimension as p;
w array of weights, one for each x;
n number of points.
Returns
MOP_SUCCESS on success.
mop_polynomial_workspace_t* mop_polynomial_workspace_alloc (gint np, gint dim, gint order)
Allocate a ::mop_polynomial_workspace_t for use in generating orthogonal polynomials.
Parameters
np (maximum) number of points in basis;
dim dimension of system;
order maximum order of polynomial to be generated.
Returns
pointer to new ::mop_polynomial_workspace.
References mop_number_of_terms().
gint mop_polynomial_workspace_free (mop_polynomial_workspace_t * w)
Free a ::mop_polynomial_workspace_t and associated memory
Parameters
w ::mop_polynomial_workspace_t to free.
Returns
MOP_SUCCESS on success.
gint mop_polynomial_write (mop_polynomial_t * p, FILE * f)
Write a ::mop_polynomial_t to a file.
Parameters
p ::mop_polynomial_t to write;
f file pointer.
Returns
MOP_SUCCESS on success.
gint mop_polynomial_write_latex (mop_polynomial_t * p, FILE * f)
Write a ::mop_polynomial_t as a fragment of LaTeX code.
Parameters
p ::mop_polynomial_t to write;
f file pointer to write to.
Returns
MOP_SUCCESS on success.