Interpolation and differentiation
Functions
gint mop_polynomial_transform (mop_polynomial_t *p, gdouble *f, gint n, gdouble *c, mop_polynomial_workspace_t *w)
gint mop_interpolate (mop_polynomial_t *p, gdouble *c, gint n, gdouble *x, gdouble *f)
gint mop_interpolation_weights (mop_polynomial_t *p, gdouble *x, gdouble *v, mop_polynomial_workspace_t *w)
gint mop_polynomial_differentiate (mop_polynomial_t *p, gdouble *x, gint *d, gdouble *P)
gint mop_differentiation_weights (mop_polynomial_t *p, gdouble *x, gint *d, gdouble *v, mop_polynomial_workspace_t *w)
Detailed Description
Function Documentation
gint mop_differentiation_weights (mop_polynomial_t * p, gdouble * x, gint * d, gdouble * v, mop_polynomial_workspace_t * w)
Compute the weights for direct differentiation at a point, based on values at the base points of a system of orthogonal polynomials, so that $\partial^{d_{1}+d_{2}+\dots}f(\mathbf{x})/\partial x_{1}^{d_{1}}x_{2}^{d_{2}}\dots\approx\sum v_{i}f_{i}$. Remember to use ::mop_polynomial_index to map base points to real points.
Parameters
p a ::mop_polynomial;
x interpolation point;
d array of derivative orders;
v differentiation weights;
w a suitably sized ::mop_polynomial_workspace.
Returns
0 on success.
References mop_polynomial_differentiate(), and mop_polynomial_eval_base().
gint mop_interpolate (mop_polynomial_t * p, gdouble * c, gint n, gdouble * x, gdouble * f)
Evaluate a function expanded in orthogonal polynomials, $f\approx\sum_{i}c_{i}P_{i}(\mathbf{x})$.
Parameters
p ::mop_polynomial_t for the expansion;
c coefficients of the expansion, from mop_polynomial_transform;
n number of function values, as in mop_polynomial_transform;
x coordinates of evaluation point;
f value(s) of function(s).
Returns
0 on success.
gint mop_interpolation_weights (mop_polynomial_t * p, gdouble * x, gdouble * v, mop_polynomial_workspace_t * w)
Compute the weights for direct interpolation at a point, based on values at the base points of a system of orthogonal polynomials, so that $f(\mathbf{x})\approx\sum v_{i}f_{i}$. Remember to use ::mop_polynomial_index to map base points to real points.
Parameters
p a ::mop_polynomial;
x interpolation point;
v interpolation weights;
w a suitably sized ::mop_polynomial_workspace.
Returns
0 on success.
References mop_polynomial_eval(), and mop_polynomial_eval_base().
gint mop_polynomial_differentiate (mop_polynomial_t * p, gdouble * x, gint * d, gdouble * P)
Evaluate derivatives of a ::mop_polynomial_t at a point x.
Parameters
p ::mop_polynomial_t to evaluate;
x coordinates of evaluation point;
d orders of differentiation for each dimension;
P array containing values of $\partial^{d_{1}+d_{2}+\dots}P(\mathbf{x})/\partial x_{1}^{d_{1}}x_{2}^{d_{2}}\dots$ at x.
Returns
0 on success.
Referenced by mop_differentiation_weights().
gint mop_polynomial_transform (mop_polynomial_t * p, gdouble * f, gint n, gdouble * c, mop_polynomial_workspace_t * w)
Calculate the coefficients of an expansion of a function f in the polynomial p.
Parameters
p ::mop_polynomial_t for the expansion;
f value(s) of function(s) at base points of p;
n number of values of $f$ at each base point;
c coefficients of expansion, $f\approx\sum_{i}c_{i}P_{i}(\mathbf{x})$;
w a ::mop_polynomial_workspace_t of appropriate size.
Returns
0 on success.
References mop_polynomial_eval_base().